/*
 * generated by Xtext
 */
package nl.cwi.reo.ui.contentassist

import nl.cwi.reo.ui.contentassist.AbstractTreoProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TreoProposalProvider extends AbstractTreoProposalProvider {
}
