var channeltypes = [
  {
    "class": "channel",
    "name": "sync",
    "end1": "source",
    "end2": "sink",
    "parts": [
      {
        "type": "line",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 150,
        "top": 150,
        "width": 100,
        "height": 0,
        "fill": "#000",
        "stroke": "#000",
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "x1": -50,
        "x2": 50,
        "y1": 0,
        "y2": 0,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 192,
        "top": 150,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 90,
        "referenceAngle": 270,
        "referenceDistance": 8,
        "referencePoint": "node2",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      }
    ]
  },
  {
    "class": "channel",
    "name": "lossysync",
    "end1": "source",
    "end2": "sink",
    "parts": [
      {
        "type": "line",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 150,
        "top": 250,
        "width": 100,
        "height": 0,
        "fill": "#000",
        "stroke": "#000",
        "strokeWidth": 1,
        "strokeDashArray": [
          8,
          8
        ],
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "x1": -50,
        "x2": 50,
        "y1": 0,
        "y2": 0,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 192,
        "top": 250,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 90,
        "referenceAngle": 270,
        "referenceDistance": 8,
        "referencePoint": "node2",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      }
    ]
  },
  {
    "class": "channel",
    "name": "syncdrain",
    "end1": "source",
    "end2": "source",
    "parts": [
      {
        "type": "line",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 150,
        "top": 350,
        "width": 100,
        "height": 0,
        "fill": "#000",
        "stroke": "#000",
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "x1": -50,
        "x2": 50,
        "y1": 0,
        "y2": 0,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 116,
        "top": 350,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 90,
        "referenceAngle": 90,
        "referenceDistance": 16,
        "referencePoint": "node1",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 184,
        "top": 350,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": -90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 270,
        "referenceAngle": 270,
        "referenceDistance": 16,
        "referencePoint": "node2",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      }
    ]
  },
  {
    "class": "channel",
    "name": "syncspout",
    "end1": "sink",
    "end2": "sink",
    "parts": [
      {
        "type": "line",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 150,
        "top": 450,
        "width": 100,
        "height": 0,
        "fill": "#000",
        "stroke": "#000",
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "x1": -50,
        "x2": 50,
        "y1": 0,
        "y2": 0,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 108,
        "top": 450,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 270,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 270,
        "referenceAngle": 90,
        "referenceDistance": 8,
        "referencePoint": "node1",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 192,
        "top": 450,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 90,
        "referenceAngle": 270,
        "referenceDistance": 8,
        "referencePoint": "node2",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      }
    ]
  },
  {
    "class": "channel",
    "name": "fifo1",
    "end1": "source",
    "end2": "sink",
    "parts": [
      {
        "type": "line",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "fill": "#000",
        "stroke": "#000",
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "x1": -50,
        "x2": 50,
        "y1": 0,
        "y2": 0,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "triangle",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 192,
        "top": 550,
        "width": 8,
        "height": 8,
        "fill": "#000",
        "stroke": null,
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 90,
        "referenceAngle": 270,
        "referenceDistance": 8,
        "referencePoint": "node2",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      },
      {
        "type": "rect",
        "version": "2.2.2",
        "originX": "center",
        "originY": "center",
        "left": 150,
        "top": 550,
        "width": 10,
        "height": 30,
        "fill": "#fff",
        "stroke": "#000",
        "strokeWidth": 1,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeLineJoin": "miter",
        "strokeMiterLimit": 10,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 90,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "clipTo": null,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "transformMatrix": null,
        "skewX": 0,
        "skewY": 0,
        "baseAngle": 90,
        "referenceAngle": 0,
        "referenceDistance": 0,
        "referencePoint": "middle",
        "rotate": true,
        "scale": false,
        "evented": false,
        "hoverCursor": "default"
      }
    ]
  },
  {
    class: "channel",
    name: "filter",
    end1: "source",
    end2: "sink",
    parts: [
      {
        type: "line",
        stroke: "#000",
        evented: false
      },
      {
        type: "triangle",
        width: 8,
        height: 8,
        fill: "#000",
        angle: 90,
        baseAngle: 90,
        referenceAngle: 270,
        referenceDistance: 8,
        referencePoint: "node2",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 135,
        referenceAngle: 90,
        referenceDistance: 42,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 45,
        referenceAngle: 90,
        referenceDistance: 28,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 135,
        referenceAngle: 90,
        referenceDistance: 14,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 45,
        referenceAngle: 90,
        referenceDistance: 0,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 135,
        referenceAngle: 90,
        referenceDistance: -14,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 45,
        referenceAngle: 90,
        referenceDistance: -28,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 135,
        referenceAngle: 90,
        referenceDistance: -42,
        referencePoint: "middle",
        scale: false,
        evented: false
      },
      {
        type: "rect",
        width: 1,
        height: 20,
        fill: "#000",
        angle: 45,
        referenceAngle: 90,
        referenceDistance: -56,
        referencePoint: "middle",
        scale: false,
        evented: false
      }
    ]
  },
  {
    class: "channel",
    name: "transformer",
    end1: "source",
    end2: "sink",
    parts: [
      {
        type: "line",
        stroke: "#000",
        evented: false
      },
      {
        type: "triangle",
        width: 8,
        height: 8,
        fill: "#000",
        angle: 90,
        baseAngle: 90,
        referenceAngle: 270,
        referenceDistance: 8,
        referencePoint: "node2",
        scale: false,
        evented: false
      },
      {
        type: "triangle",
        width: 20,
        height: 20,
        fill: "#FFF",
        stroke: "rgb(0, 0, 0)",
        angle: 90,
        baseAngle: 90,
        referenceAngle: 270,
        referenceDistance: 0,
        referencePoint: "middle",
        scale: false,
        evented: false
      }
    ]
  }
];