/*
 * generated by Xtext 2.11.0.RC2
 */
package nl.cwi.reo


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TreoRuntimeModule extends AbstractTreoRuntimeModule {
}
