#!/bin/bash
  BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "
#!/bin/bash

alias reo=\"java -jar $BASEDIR/bin/reo-1.0.jar\"

export CLASSPATH=\"$CLASSPATH:.:$BASEDIR/bin/reo-runtime-java.jar:$BASEDIR/bin/reo-runtime-java-lykos.jar\"
" >> $BASEDIR/initreo.sh

echo "
===================================
=                                 =
=   README for Reo installation   =
=                                 =
===================================

=============
Linux and Mac
=============

<<<<<<< HEAD
To compile the Java code generated by Reo, it is necessary to link the runtime library. 
To configure Reo for your current shell, execute the following commands:

        >$ source $BASEDIR/initreo.sh

If you want to make Reo automatic for each Shell sessions, append the startup script ~/.bashrc with the following commands:
=======
You need to set some environment variable before being able to use Reo. 
To configure reo for your current shell, execute the following commands:
>>>>>>> 2289fbda196013360271d20734b412124fd2f6d0

        >$ export CLASSPATH=\"\$CLASSPATH:.:$BASEDIR/bin/reo-runtime-java.jar:$BASEDIR/bin/reo-runtime-java-lykos.jar\"

        >$ alias reo=\"java -jar $BASEDIR/bin/reo-1.0.jar\"

For the changes to take effect, run

        >$ source ~/.bashrc

======
How to compile and run examples : 
======
Go to folder \"examples/slides/main\" and execute : 

        >$  reo FILE.treo -cp ../.. -o OUTPUT_DIR 

The option -cp indicate the classpath for reo dependencies. The option -o is the output directory.
Moove to the OUTPUT_DIR and compile the file with : 

        >$  javac OUTPUT_DIR/*.java 

Note that if you are using external java classes, you should first compile those classes before compiling the generated code. 
Run the application with : 

        >$  java FILE


" >> $BASEDIR/README

