/*
 * generated by Xtext 2.11.0.RC2
 */
package nl.cwi.reo.ide

import com.google.inject.Guice
import nl.cwi.reo.TreoRuntimeModule
import nl.cwi.reo.TreoStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TreoIdeSetup extends TreoStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TreoRuntimeModule, new TreoIdeModule))
	}
	
}
