/*
 * generated by Xtext 2.11.0.RC2
 */
package nl.cwi.reo.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TreoUiModule extends AbstractTreoUiModule {
}
